export const mockChatList = [
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    name: 'Team Alpha',
    lastSenderUsername: 'Alex',
    lastSenderMessage: 'Митинг перенесли на завтра в 10:00',
    lastSenderMessageTime: '09:45',
    newMessagesCount: 3,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=2',
    name: 'Design Review',
    lastSenderUsername: 'Mia',
    lastSenderMessage: 'Скинула обновлённый макет в Figma',
    lastSenderMessageTime: 'Вчера',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=3',
    name: 'Backend Devs',
    lastSenderUsername: 'Dmitry',
    lastSenderMessage: 'API готово, можно интегрировать',
    lastSenderMessageTime: '14:22',
    newMessagesCount: 1,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=4',
    name: 'Marketing',
    lastSenderUsername: 'Elena',
    lastSenderMessage: 'Нужно одобрить текст рассылки',
    lastSenderMessageTime: '13:10',
    newMessagesCount: 5,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    name: 'Support Tickets',
    lastSenderUsername: 'Bot',
    lastSenderMessage: 'Новое обращение #7821 от клиента',
    lastSenderMessageTime: '11:30',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=6',
    name: 'Project Phoenix',
    lastSenderUsername: 'Ivan',
    lastSenderMessage: 'Дедлайн сдвинули на 15 июня',
    lastSenderMessageTime: 'Вчера',
    newMessagesCount: 2,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=7',
    name: 'HR Announcements',
    lastSenderUsername: 'HR Bot',
    lastSenderMessage: 'Завтра — день здоровья в офисе!',
    lastSenderMessageTime: '10:05',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=8',
    name: 'Frontend Guild',
    lastSenderUsername: 'Sofia',
    lastSenderMessage: 'Кто хочет ревью PR с новым хуком?',
    lastSenderMessageTime: '09:15',
    newMessagesCount: 7,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
    name: 'DevOps Alerts',
    lastSenderUsername: 'AlertBot',
    lastSenderMessage: 'CPU usage на prod сервере > 90%',
    lastSenderMessageTime: '08:55',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=10',
    name: 'Product Ideas',
    lastSenderUsername: 'Nikita',
    lastSenderMessage: 'Добавим тёмную тему в следующем спринте?',
    lastSenderMessageTime: 'Вчера',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=11',
    name: 'Client — Acme Corp',
    lastSenderUsername: 'Client',
    lastSenderMessage: 'Отличная работа! Готовы к следующему этапу',
    lastSenderMessageTime: '16:40',
    newMessagesCount: 1,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    name: 'Random',
    lastSenderUsername: 'Pavel',
    lastSenderMessage: 'Кто идёт в кофейню в 15:00?',
    lastSenderMessageTime: '14:55',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
    name: 'Security Team',
    lastSenderUsername: 'Anna',
    lastSenderMessage: 'Обязательно обновите 2FA до пятницы',
    lastSenderMessageTime: '12:30',
    newMessagesCount: 4,
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
    name: 'QA Channel',
    lastSenderUsername: 'Oleg',
    lastSenderMessage: 'Нашёл баг в форме авторизации',
    lastSenderMessageTime: '11:20',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    name: 'Learning Club',
    lastSenderUsername: 'Maria',
    lastSenderMessage: 'Сегодня обсуждаем Zustand vs Redux',
    lastSenderMessageTime: '10:10',
    newMessagesCount: 2,
  },
];